apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: rhtap-chatbot-app-16
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/mvaldron-rhdh/rhtap-chatbot-app-16:12d87f5c3b895c5eec3fb5e34b104e15649e9a7a@sha256:b632713c6bc58d14a84eaee00141bb2163fbb8f74e8e7153dd67ad86552d16cd
        name: container-image  
